### PR TITLE
Fix oil_pwm setup. Needs remapping to PE9

### PR DESCRIPTION
**Pull request by streber42**
As is INV_POWER and OIL_PWM are trying to share PA8.

### CODE REVIEW

**Review by cgalpin — CHANGES_REQUESTED** [review]
Can you also update the comment on those lines in hwinit.cop as well please? Right now it’s misleading.

**Comment by streber42** [comment]
Fixed, sorry thought I had already done that.

**Comment by streber42** [comment]
Missed this one the first time.

**Comment by damienmaguire** [comment]
Many thanks

**Pull request merged**
